tap "homebrew/bundle"
tap "homebrew/core"

# Binaries
brew "git"
brew "node"

# Essentials 
brew "fzf"
brew "autojump"
brew "gawk"
brew "genupg"
brew "stow"
brew "zsh"

# Development
brew "asdf"
brew "linear-linear"

# Apps
cask "kap"
cask "github"
cask "slack"
cask "spotify"
cask "raycast"
cask "google-chrome"
cask "visual-studio-code"
cask "obs-studio"
